### ISSUE TITLE
Have orders auto mention Sandwich Artists

### ISSUE THREAD

**Issue by LewisTehMinerz** [USRDiscordBots/Sandwich-Delivery-Bot-2.0#10]

**Comment by Fires1** [comment]
https://github.com/USRDiscordBots/Sandwich-Delivery-Bot-2.0/commit/e96d4904110b03f7719bbb798dcccfdc79c29825

**Comment by LewisTehMinerz** [comment]
a9dee15fcddab7f20dbd7f77b0e033b8695c83c7 <= actually mentions them
